# Generated by Django 6.0.6 on 2026-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dacha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('nomi', models.CharField(max_length=100)),
                ('address', models.IntegerField()),
                ('soni', models.IntegerField()),
                ('narx', models.IntegerField()),
                ('date', models.DateField()),
                ('date2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='uzum_market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('nomi', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('soni', models.IntegerField()),
                ('chegirma', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
